services:
  crenaux:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - SESSION_SECRET=${SESSION_SECRET}
      - ORIGIN=${ORIGIN}
      - DATA_DIR=/data
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-network'

      # HTTP & redirect
      - 'traefik.http.routers.crenaux-http.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.crenaux-http.entrypoints=web'
      - 'traefik.http.routers.crenaux-http.middlewares=redirect-to-https@docker'

      # HTTPS
      - 'traefik.http.routers.crenaux.rule=Host(`${DOMAIN}`)'
      - 'traefik.http.routers.crenaux.entrypoints=websecure'
      - 'traefik.http.routers.crenaux.tls.certresolver=letsencrypt'

      # docker port
      - 'traefik.http.services.crenaux.loadbalancer.server.port=3000'
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
